#if !canImport(ObjectiveC)
import XCTest

extension ConsoleStringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConsoleStringTests = [
        ("testStringBackgroundColor", testStringBackgroundColor),
        ("testStringClearMode", testStringClearMode),
        ("testStringColor", testStringColor),
        ("testStringMultipleModes", testStringMultipleModes),
        ("testStringStyle", testStringStyle),
    ]
}

extension RainbowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RainbowTests = [
        ("testExtractModes", testExtractModes),
        ("testExtractModesNotMatch", testExtractModesNotMatch),
        ("testGenerateConsoleStringWithCodes", testGenerateConsoleStringWithCodes),
        ("testGenerateUnknownStringWithCodes", testGenerateUnknownStringWithCodes),
        ("testGenerateXcodeColorsStringWithCodes", testGenerateXcodeColorsStringWithCodes),
        ("testRainbowEnabled", testRainbowEnabled),
        ("testRainbowRawString", testRainbowRawString),
    ]
}

extension XcodeColorsStringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XcodeColorsStringTests = [
        ("testStringBackgroundColor", testStringBackgroundColor),
        ("testStringClearMode", testStringClearMode),
        ("testStringColor", testStringColor),
        ("testStringMultipleModes", testStringMultipleModes),
        ("testStringStyle", testStringStyle),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ConsoleStringTests.__allTests__ConsoleStringTests),
        testCase(RainbowTests.__allTests__RainbowTests),
        testCase(XcodeColorsStringTests.__allTests__XcodeColorsStringTests),
    ]
}
#endif
