fastlane_version "2.230.0"

require "tempfile"

default_platform :mac

platform :mac do
  def read_changelog_section(version:)
    content = File.read("CHANGELOG.md")
    pattern = /^## \\[#{Regexp.escape(version)}\\].*?\\n(.*?)(?=^## \\[|\\z)/m
    match = content.match(pattern)
    UI.user_error!("Missing CHANGELOG.md section for #{version}") unless match
    match[1].strip
  end

  def github_release_exists?(version:)
    begin
      sh("gh release view #{version} --repo onevcat/Rainbow", log: false)
      true
    rescue
      false
    end
  end

  def create_github_release(version:)
    return if github_release_exists?(version: version)

    notes = read_changelog_section(version: version)
    Tempfile.create(["release_notes_", ".md"]) do |file|
      file.write(notes + "\n")
      file.flush
      sh("gh release create #{version} --repo onevcat/Rainbow --title \"#{version}\" --notes-file #{file.path}")
    end
  end

  def update_unreleased_compare_link(tag:)
    changelog_path = "CHANGELOG.md"
    content = File.read(changelog_path)
    unless content.match?(/^\[Unreleased\]: .+$/)
      UI.user_error!("Missing [Unreleased] link reference in #{changelog_path}")
    end
    updated = content.gsub(/^\[Unreleased\]: .*$/, "[Unreleased]: https://github.com/onevcat/Rainbow/compare/#{tag}...HEAD")
    File.write(changelog_path, updated)
  end

  desc "Runs all the tests"
  lane :test do
    spm(command: "test")
  end
    
  desc "Release new version"
  lane :release do |options|
      target_version = options[:version]
      raise "The version is missed. Use `fastlane release version:{version_number}`.`" if target_version.nil?
      
      ensure_git_branch
      ensure_git_status_clean
      scan
      
      build_number = number_of_commits
      increment_build_number(build_number: build_number)
      
      increment_version_number(version_number: target_version)
      version_bump_podspec(path: "RainbowSwift.podspec", version_number: target_version)

      stamp_changelog(section_identifier: target_version, git_tag: target_version, stamp_datetime_format: "%F")
      update_unreleased_compare_link(tag: target_version)

      git_commit_all(message: "Bump version to #{target_version}")
      add_git_tag tag: target_version
      
      push_to_git_remote
      create_github_release(version: target_version)
      pod_push
  end

  lane :podpush do
    pod_push
  end
  
end
